

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb 
    restart: unless-stopped 
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data:
    driver: local
